-- Creating role
CREATE OR REPLACE ROLE DATA_ENGINEER_ROLE;

-- Granting usage on warehouse
GRANT USAGE 
ON WAREHOUSE OLIST_WH 
TO ROLE DATA_ENGINEER_ROLE;

-- Granting usage on database
GRANT USAGE
ON DATABASE OLIST_DW
TO ROLE DATA_ENGINEER_ROLE;

-- Granting all privileges on schemas
GRANT ALL PRIVILEGES
ON SCHEMA OLIST_DW.SOURCE_DATA
TO ROLE DATA_ENGINEER_ROLE;

GRANT ALL PRIVILEGES
ON SCHEMA OLIST_DW.ANALYTICS
TO ROLE DATA_ENGINEER_ROLE;

-- Assigning role to user
GRANT ROLE DATA_ENGINEER_ROLE TO USER AndileZulu260;