USE ROLE DATA_ENGINEER_ROLE;
USE DATABASE OLIST_DW;

-- Stores customer details and their location (city, state, zip code)
CREATE OR REPLACE TABLE OLIST_DW.SOURCE_DATA.CUSTOMERS(
CUSTOMER_ID VARCHAR,
CUSTOMER_UNIQUE_ID VARCHAR,
CUSTOMER_ZIP_CODE_PREFIX VARCHAR,
CUSTOMER_CITY VARCHAR,
CUSTOMER_STATE VARCHAR
);

-- Holds latitude and longitude coordinates for each zip code prefix
CREATE OR REPLACE TABLE OLIST_DW.SOURCE_DATA.GEOLOCATION(
GEOLOCATION_ZIP_CODE_PREFIX VARCHAR,
GEOLOCATION_LAT FLOAT,
GEOLOCATION_LNG FLOAT,
GEOLOCATION_CITY VARCHAR,
GEOLOCATION_STATE VARCHAR
);

-- Contains each item within an order, including price and shipping info
CREATE OR REPLACE TABLE OLIST_DW.SOURCE_DATA.ORDER_ITEMS(
ORDER_ID VARCHAR,
ORDER_ITEM_ID INT,
PRODUCT_ID VARCHAR,
SELLER_ID VARCHAR,
SHIPPING_LIMIT_DATE TIMESTAMP,
PRICE FLOAT,
FREIGHT_VALUE FLOAT
);

-- Tracks how each order was paid (credit card, boleto, etc.) and in how many installments
CREATE OR REPLACE TABLE OLIST_DW.SOURCE_DATA.ORDER_PAYMENTS(
ORDER_ID VARCHAR,
PAYMENT_SEQUENTIAL INT,
PAYMENT_TYPE VARCHAR,
PAYMENT_INSTALLMENTS INT,
PAYMENT_VALUE FLOAT
);

-- Captures customer review scores and optional comments after delivery
CREATE OR REPLACE TABLE OLIST_DW.SOURCE_DATA.ORDER_REVIEWS(
REVIEW_ID VARCHAR,
ORDER_ID VARCHAR,
REVIEW_SCORE INT,
REVIEW_COMMENT_TITLE VARCHAR,
REVIEW_COMMENT_MESSAGE VARCHAR,
REVIEW_CREATION_DATE TIMESTAMP,
REVIEW_ANSWER_TIMESTAMP TIMESTAMP
);

-- Tracks each order from purchase through approval, shipping, and delivery
CREATE OR REPLACE TABLE OLIST_DW.SOURCE_DATA.ORDERS(
ORDER_ID VARCHAR,
CUSTOMER_ID VARCHAR,
ORDER_STATUS VARCHAR,
ORDER_PURCHASE_TIMESTAMP TIMESTAMP,
ORDER_APPROVED_AT TIMESTAMP,
ORDER_DELIVERED_CARRIER_DATE TIMESTAMP,
ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP,
ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP
);

-- Product catalog with category, dimensions, weight, and photo count
CREATE OR REPLACE TABLE OLIST_DW.SOURCE_DATA.PRODUCTS(
PRODUCT_ID VARCHAR,
PRODUCT_CATEGORY_NAME VARCHAR,
PRODUCT_NAME_LENGHT INT,
PRODUCT_DESCRIPTION_LENGHT INT,
PRODUCT_PHOTOS_QTY INT,
PRODUCT_WEIGHT_G INT,
PRODUCT_LENGTH_CM INT,
PRODUCT_HEIGHT_CM INT,
PRODUCT_WIDTH_CM INT
);

-- Seller information and where they're located
CREATE OR REPLACE TABLE OLIST_DW.SOURCE_DATA.SELLERS(
SELLER_ID VARCHAR,
SELLER_ZIP_CODE_PREFIX VARCHAR,
SELLER_CITY VARCHAR,
SELLER_STATE VARCHAR
);

-- Translates product category names from Portuguese to English
CREATE OR REPLACE TABLE OLIST_DW.SOURCE_DATA.PRODUCT_CATEGORY_TRANSLATION(
PRODUCT_CATEGORY_NAME VARCHAR,
PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR
);