-- Creating a data warehouse
CREATE OR REPLACE WAREHOUSE OLIST_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Creating a database and using database created
CREATE OR REPLACE DATABASE OLIST_DW;
USE DATABASE OLIST_DW;

-- Creating schemas
CREATE OR REPLACE SCHEMA SOURCE_DATA;
CREATE OR REPLACE SCHEMA ANALYTICS;
